service: hello-you

package:
  exclude:
    - .gitignore
    - .git/**
    - node_modules/**
    - package.json

plugins:
  - serverless-google-cloudfunctions
provider:
  name: google
  runtime: python37
  project: ${opt:project}
  credentials: ~/.gcloud/keyfile.json

functions:
  hello:
    handler: hello_you
    events:
      - http: path
